root = "."
tmp_dir = ".tmp"

[build]
cmd = "go build -o .tmp/main ."
bin = ".tmp/main"
full_bin = ".tmp/main -f example-labels.yaml --debug --dashboard"
include_ext = ["go", "html"]
exclude_dir = [".tmp"]
include_dir = []
exclude_file = []
exclude_regex = []
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000
stop_on_error = false
send_interrupt = false

[misc]
clean_on_exit = true
