language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.16.x
before_install:
  - go get -t -v ./...
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -i -a -o ./test.windows.amd64.exe .
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -i -a -o ./test.darwin.amd64 .
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -i -a -o ./test.linux.amd64 .
